apiVersion: v1
kind: Service
metadata:
  name: myflaskapp-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '5000'
spec:
  type: LoadBalancer
  selector:
    app: myflaskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
